# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN yarn build

EXPOSE 8080

# Start the MCP server
CMD [ "node", "./build/index.js" ]
